"""Initial Migration

Revision ID: 7332a27f7a14
Revises: 7ed16cd95faa
Create Date: 2022-05-09 06:45:05.927376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7332a27f7a14'
down_revision = '7ed16cd95faa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
